apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: development
  name: dev
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "services"]
    verbs: ["create", "delete", "update", "get", "list", "watch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devops
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "namespaces", "services", "secrets"]
    verbs: ["create", "delete", "update", "get", "list", "watch"]